defaults:
  - _pipeline
  - stage_configs:
      - fit_normalization
      - fit_vocabulary_indices
  - _self_

input_dir: ${oc.env:INPUT_DIR}
cohort_dir: ${oc.env:OUTPUT_DIR}

etl_metadata.pipeline_name: "tensorization"

stage_configs:
  tokenization:
    _script: "MTD_tokenize"
  tensorization:
    _script: "MTD_tensorize"

# Pipeline Structure
stages:
  - fit_normalization
  - fit_vocabulary_indices
  - normalization
  - tokenization
  - tensorization
